### PR TITLE
packer and vagrant intro to repository

### PR DESCRIPTION
**Pull request by kayiwa**
This commit adds a packer json file and a Vagrant file. Both will spin up a working redis container. As soon as I fix the docker images on docker hub both will have a the dnflow working.

### CODE REVIEW

**Comment by kayiwa** [comment]
packer and vagrant build correctly. Documentation on how to do this will be coming once I fix the images.

**Comment by edsu** [comment]
I somehow missed this till now. Does it still make sense to merge this in, or are we going to be putting this into another github repository?

**Comment by kayiwa** [comment]
reject it for now. New one coming up later today.

**Comment by edsu** [comment]
👍

**Pull request closed without merging**
