### PR TITLE
new vagrantfile

### PR DESCRIPTION
**Pull request by kayiwa**
This commit allows a user to run dnflow on virtualbox locally. It is most useful in helping me design the docker containers where they will finally rest. Others may find it useful for development purposes.

### CODE REVIEW

**Comment by kayiwa** [comment]
updated Vagrantfile for rapid prototyping.

**Comment by edsu** [comment]
@kayiwa is this typical to intersperse packer configuration, etc with the actual application that is being packaged -- in the same repository?  I have definitely seen Vagrant files combined with application repositories, but not Packer.

**Comment by kayiwa** [comment]
good question that I haven't an answer for at the moment @edsu I think of them as no different from the Vagrantfile (in that both create a reproducible lightweight environment), but will spend some time seeing what others have done.

**Comment by kayiwa** [comment]
created a new docnow-ansible repo.

**Pull request closed without merging**
